### ISSUE TITLE
Incompatibility with kt-paperclip

### ISSUE THREAD

**Issue by jwoodrow** [Shopify/yjit#306] opened 2023-01-10 17:02 UTC
Hi, first off good work on YJIT.

I've been trying to upgrade to ruby 3.2 with YJIT enabled and noticed some issues with the kt-paperclip when used with rails.

We have an old model we haven't attempted to migrate to active_storage because of the sheer size of this model and so we have kt-paperclip still in the project for this. In our demo generation suite (using factorybot) we end up using the `model_instance.attachment.assign` method which then calls some validations but doing so seems to completely break when using yjit.

Here is the error and the stack trace if it can help:

```bash
NoMethodError: undefined method `_read_attribute' for :read_attribute_for_validation:Symbol
/home/docker/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4/lib/active_model/attribute_methods.rb:277:in `attachment_file_name'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/validators/attachment_file_name_validator.rb:19:in `validate_each'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4/lib/active_model/validator.rb:153:in `block in validate'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4/lib/active_model/validator.rb:149:in `each'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activemodel-7.0.4/lib/active_model/validator.rb:149:in `validate'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/validators.rb:68:in `block in create_validating_before_filter'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:445:in `instance_exec'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:445:in `block in make_lambda'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:199:in `block (2 levels) in halting'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/callbacks.rb:28:in `block in hasta_la_vista_baby'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:200:in `block in halting'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `block in invoke_before'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `each'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:595:in `invoke_before'
/home/docker/bundle/vendor/ruby/3.2.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:106:in `run_callbacks'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/callbacks.rb:38:in `run_paperclip_callbacks'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:504:in `check_validity?'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:494:in `post_process'
/home/docker/bundle/vendor/ruby/3.2.0/gems/kt-paperclip-7.1.1/lib/paperclip/attachment.rb:454:in `post_process_file'
```

I know this is linked to YJIT because if I remove the `RUBYOPT="--enable-yjit"` before running the demo generation then everything works fine.

I don't understand exactly why this is happening, but I'm guessing/hoping I'm not the only one encountering issues using YJIT + kt-paperclip.

Maybe this is an issue I should raise on the kt-paperclip repo but I have a feeling it's more like some missing implementations in YJIT than kt-paperclip being broken (since it still works fine with the default cruby). Any insight into resolving this would be welcome ! 👋

**Comment by maximecb** [comment] 2023-01-10 18:50
Hi @jwoodrow,

Can you provide more context in terms of what machine you are running this on (Mac/Linux distro, are you on an x86 or ARM machine?).

Would also like to know if you can provide a minimal script that reproduces the error and which command you've used to run it. I've never heart of kt-paperclip or factorybot before, and I don't know which codebase you're running this on, so I wouldn't know how to reproduce this issue.

**Comment by maximecb** [comment] 2023-01-10 19:16
If you're able to provide us with the smallest possible script that reproduces the problem, that will help us a lot in diagnosing and fixing the issue. If there's something wrong with the way we handle symbols, that is definitely something we want to fix.

**Comment by maximecb** [comment] 2023-01-11 15:07
Ok, well, if there is an issue with symbols, it will probably get fixed eventually when we can get a repro from another source :)

**Comment by geoffharcourt** [comment] 2023-01-19 14:11
Possibly related: we had something happen to us inconsistently but frequently in CI that went away as soon as we disabled YJIT. We haven't seen this in production and haven't been able to reproduce it on our development machines: 

https://github.com/kreeti/kt-paperclip/issues/107

**Comment by XrXr** [comment] 2023-01-19 14:22
I suggest trying a build of YJIT off of the master branch. We've landed a couple of bug fixes since the 3.0 release that haven't been released yet. You can follow instructions to build from a checkout, or use https://github.com/rbenv/ruby-build with a checkout or a [nightly snapshot release tar ball](https://github.com/rbenv/ruby-build). There are also nightly builds of container images available at <https://hub.docker.com/r/rubylang/ruby>.

**Comment by maximecb** [comment] 2023-01-19 15:15
@geoffharcourt if you have the time, checking if this bug is fixed by building ruby master as Alan suggested would be very helpful.

**Comment by johnnyshields** [comment] 2023-01-29 18:37
FYI -- at TableCheck we're running kt-paperclip and YJIT in production and not seeing any issues.

**Comment by maximecb** [comment] 2023-01-30 16:11
> FYI -- at TableCheck we're running kt-paperclip and YJIT in production and not seeing any issues so far.

Thanks for the feedback @johnnyshields. Also very happy to hear that you are running YJIT in production :)

Will leave this issue open for a little bit longer, just in case anyone else has anything to report.

**Comment by josh-m-sharpe** [comment] 2023-02-09 21:32
Hi all 👋  - I can reproduce this (or very similar) issue in our local test suite (rails 6.1.x / ruby 3.2.1 yjit / kt-paperclip).  Interestingly it only fails if I run the suite or multiple tests files/methods at once.  It doesn't fail if I run the single test method (e.g. rails test path/to/test.rb:134)

@maximecb can you confirm if the fixes you speak of are a part of 3.2.1 or should I attempt with master?

(Also hey there @geoffharcourt - long time.  Hope you're well!)

**Comment by josh-m-sharpe** [comment] 2023-02-09 22:09
I’ve seen it fail with both 3.2.0 and 3.2.1. 

I’m open to pairing. I usually work EST 9-5.  Please let me know how best we can schedule a time. Thanks!

**Comment by maximecb** [comment] 2023-02-10 19:35
Tentatively Tuesday, Wednesday or Thursday in the afternoon would work best for us. Would that work for you as well?

We typically use Tuple for pairing, but we could use another solution if you prefer another platform. You'll need to have the rust toolchain and lldb or gdb installed.

**Comment by maximecb** [comment] 2023-02-27 16:13
Hi there. Alan just merged a PR which he believes may fix this problem.

If someone could test whether the bug is fixed by commit [0eb634a](https://github.com/ruby/ruby/commit/0eb634ae73cb327ede833b72492f912792a4a9d5), that would be very helpful.

Have a great week everyone :)

**Comment by XrXr** [comment] 2023-02-27 23:45
The commit landed patches 3.2.1 cleanly, so you can try it without making your app compatible with the latest development version of Ruby. Here is how to build with the patch (the build takes less than 10 minutes!):

If you use `ruby-install` (I tried on an ARM64 Mac):
```shell
ruby-install ruby 3.2.1 \
                      --jobs 8 \
                      --no-reinstall \
                      --install-dir ~/.rubies/ruby-yjit-send-fix \
                      --patch https://github.com/ruby/ruby/commit/0eb634ae73cb327ede833b72492f912792a4a9d5.patch \
                      -- --enable-yjit
```

If you use `rbenv` with `ruby-build` (I tried on `x86_64-linux-gnu`):
```shell
# make sure `rustc` is available and works
rbenv install --patch 3.2.1 \
	< <(curl --proto '=https' --tlsv1.2 -sSf https://github.com/ruby/ruby/commit/0eb634ae73cb327ede833b72492f912792a4a9d5.patch)
```

Depending on your setup, you might not even need to reinstall the bundle for your Rails app when switching to the patched version.

Let us know how it goes if you do decide to give this a go! It'd be valuable feedback for us and for the release manager for the `3.2.x` series.

**Comment by josh-m-sharpe** [comment] 2023-02-28 01:45
@maximecb @XrXr  I managed to get ruby build from master downloaded here https://github.com/ruby/ruby - which seems to resolve this issue - at least, our test suite has passed.  

Any guess as to when 3.2.2 might drop?  It'll be much easier to further test this patch with a released version.

Thank you!

**Comment by XrXr** [comment] 2023-02-28 15:08
> Any guess as to when 3.2.2 might drop?

Generally, the branch maintainer decides the timing and the contents of releases. I think @nurse is the current maintainer of the [`ruby_3_2`](https://github.com/ruby/ruby/commits/ruby_3_2) branch. Historically, there are gaps measured in weeks between releasees, but past results do not necessarily predict the future.

> Thank you!

Thank _you_ for testing!

**Closed by XrXr** 2023-02-28 15:08 UTC
